

export let ApiConfig = {
    'BASEURL': '',
    'WEBURL': '',
    'HEALTH': '/health/ok',
    'INFO': '/common/info',
    'LOGIN': '/user/login',
    'DETAILS': '/user/details?username=%uname%',
    'SAVE_CATEGORY': "/admin/category/save",
    'GET_CATEGORIES': "/admin/categories/all",
    'GET_CATEGORY': "/admin/category/%id%",
    'DELETE_CATEGORY': "/admin/category/%id%/delete",
    'GET_SUB_CATEGORIES': "/admin/category/%id%/subcategories/all",
    'GET_SUB_CATEGORY': "/admin/subcategory/%id%",
    'SAVE_SUB_CATEGORY': "/admin/category/%id%/subcategory/save",
    'DELETE_SUB_CATEGORY': "/admin/subcategory/%id%/delete",
    'GET_SERVICES': "/admin/services/all",
    'GET_SERVICE': "/admin/service/%id%",
    'SAVE_SERVICE': "/admin/service/save",
    'DELETE_SERVICE': "/admin/service/%id%/delete",
    'GET_AREAS': "/admin/areas/all",
    'GET_AREA': "/admin/area/%id%",
    'SAVE_AREA': "/admin/area/save",
    'DELETE_AREA': "/admin/area/%id%/delete",
    'GET_VENDORS': "/admin/vendors/all",
    'GET_VENDOR': "/admin/vendor/%id%",
    'GET_DETAIL': "/admin/vendor/%id%/detail",
    'SAVE_VENDOR':  "/admin/vendor/save",
    'DELETE_VENDOR': "/admin/vendor/%id%/delete",
    'SAVE_ADDRESS': "/admin/vendor/%id%/address/save",
    'ADDRESS_BY_VENDOR': "/admin/vendor/%id%/address",
    'SAVE_CONTACT': "/admin/vendor/%id%/contact/save",
    'CONTACT_BY_VENDOR': "/admin/vendor/%id%/contact",
    'SAVE_VENDOR_SERVICES': "/admin/vendor/%id%/services/save",
    'SERVICES_BY_VENDOR': "/admin/vendor/%id%/services",
    'CLASS_RANGE': "/admin/classrange",
    'GET_LOGO': "/admin/vendor/%id%/logo",
    'UPLOAD_LOGO': "/admin/vendor/%id%/logo/upload",
    'DELETE_LOGO': "/admin/vendor/%id%/logo/delete?key=%key%",
    'GET_GALLERY': "/admin/vendor/%id%/gallery",
    'UPLOAD_GALLERY': "/admin/vendor/%id%/gallery/upload",
    'DELETE_GALLERY': "/admin/vendor/%id%/gallery/delete?key=%key%"
};
